version: '2'
services:
  web:
    container_name: question-api
    build:
      context: ./src
      dockerfile: Services/Question.API/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=sqlserver,1433;Database=Question;User=sa;Password=password1234;
      - KafkaConfiguration:BootstrapServer=kafka:9092
      - Seq:ServerUrl=seq:5341
    networks:
      - questionnetwork
    depends_on:
      - db
      - kafka
      - sql-server-db
      - seq
    command: ["dotnet", "ef", "database update"]

  worker:
    container_name: worker-analytics
    build:
      context: ./src
      dockerfile: Workers/Question.Analytics/Dockerfile
    networks:
      - questionnetwork
    depends_on:
      - mongo
      - kafka
      - seq
    environment:
      - ConnectionStrings:DefaultConnection=mongodb://mongo:27017/analytic
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - Seq:ServerUrl=seq:5341

  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=analytics
    networks:
      - questionnetwork

  zookeeper:
    container_name: zookeeper
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - questionnetwork

  kafka:
    container_name: kafka
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CREATE_TOPICS=questionCreated:1:1
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - questionnetwork

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=kafka:2181
    networks:
      - questionnetwork

  sql-server-db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1439:1433"
    environment:
      SA_PASSWORD: "password1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    networks:
      - questionnetwork
    volumes:
      - sqlvolume:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

volumes:
  sqlvolume:
    driver: local

networks:
  questionnetwork:
    external: false